### ISSUE TITLE
problem with the captcha?

### ISSUE THREAD

**Issue by stchang** [vishesh/whalebin#18]
I'm getting a captcha error when trying to upload a program:

```
tcp-connect: connection failed
  detail: host not found
  address: www.google.com
```

**Comment by vishesh** [comment]
I got same error. For now I restarted the server and its working again. Any ideas why it may have happened?

**Comment by stchang** [comment]
Ok it's working now for me as well. Don't know what happened. At the time, I checked pasterack and the captcha was still working there. Weird.
