### ISSUE TITLE
Website: too many open files

### ISSUE THREAD

**Issue by greggraham** [vishesh/whalebin#20]
I get the following message when trying to run a program or look at the source code of a program on http://bigbang.ccs.neu.edu/.

Exception
The application raised an exception with the message:

open-input-file: cannot open input file
  path: /home/whalebin/whalebin/data/outputs/e7/e7iQm
  system error: Too many open files; errno=24
Stack trace:

f415 at:
  <unknown location>
<unknown procedure> at:
  line 58, column 2, in file /usr/share/racket/pkgs/web-server-lib/web-server/dispatchers/dispatch-servlets.rkt
select-handler/no-breaks at:
  line 162, column 2, in file /usr/share/racket/collects/racket/private/more-scheme.rkt
<unknown procedure> at:
  line 112, column 8, in file /usr/share/racket/pkgs/web-server-lib/web-server/private/dispatch-server-unit.rkt

**Comment by stchang** [comment]
This problem seems to have occurred again. @vishesh can you kick the server?

**Comment by vishesh** [comment]
Fixed the problem and restarted the server.
